# Generated by Django 3.0.5 on 2020-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200618_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='图片',
            field=models.TextField(),
        ),
    ]
