# Generated by Django 3.0.5 on 2020-06-18 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200618_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='链接',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='标题',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
